<?php
require '/var/www/html/vendor/autoload.php';
$app = require '/var/www/html/bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use FalconCms\Core\Models\Post;
use FalconCms\Core\Models\ProductData;

$products = [

'iphone-15-pro' => [
'content' => '<p>The iPhone 15 Pro represents Apple\'s pinnacle of smartphone engineering, combining cutting-edge technology with premium aerospace-grade titanium materials. At its core lies the revolutionary A17 Pro chip, built on a groundbreaking 3-nanometer process that delivers unprecedented CPU and GPU performance while maintaining exceptional battery efficiency. This powerhouse processor enables console-quality gaming experiences, advanced on-device machine learning, and seamless multitasking across demanding professional applications.</p>
<p>The titanium design makes the iPhone 15 Pro the lightest Pro model Apple has ever produced, while the textured matte glass back provides a luxurious feel and confident grip. Ceramic Shield front glass offers four times better drop protection compared to any competing smartphone glass technology currently available on the market.</p>
<p>Photography enthusiasts will marvel at the versatile 48MP main camera system featuring a second-generation sensor with larger pixels for superior low-light performance. The new 5x Telephoto lens allows you to capture stunning portrait shots and distant subjects with remarkable detail and clarity. The 12MP Ultra Wide camera includes autofocus capability for impressive macro photography, while advanced Night mode and Photonic Engine processing ensure consistently beautiful results regardless of lighting conditions.</p>
<p>USB-C connectivity finally arrives on iPhone 15 Pro, enabling data transfer speeds up to 10Gb/s with USB 3 support — delivering speeds up to 20 times faster than the previous Lightning connector. The fully customizable Action Button replaces the traditional mute switch and provides instant one-press access to your most frequently used features and shortcuts.</p>
<p>The stunning Super Retina XDR display with ProMotion technology delivers an incredibly smooth 120Hz refresh rate that intelligently adapts between 1Hz and 120Hz based on displayed content. The Always-On display keeps your essential information visible at a glance without significantly impacting battery life. Available in Natural Titanium, Blue Titanium, White Titanium, and Black Titanium color options.</p>',
'short_description' => '<p>The iPhone 15 Pro is Apple\'s most powerful smartphone, driven by the A17 Pro chip on a 3-nanometer process for exceptional performance. The lightweight titanium frame houses a 48MP camera system with 5x optical zoom, USB-C with USB 3 speeds, and a customizable Action Button. The 6.1-inch Super Retina XDR ProMotion display with Always-On technology delivers a premium viewing experience, while advanced computational photography and iOS 17 features make this the ultimate tool for creative professionals and power users.</p>',
],

'samsung-galaxy-s24-ultra' => [
'content' => '<p>The Samsung Galaxy S24 Ultra stands as the undisputed flagship of Samsung\'s 2024 lineup, engineered for professionals and power users who demand the absolute best in mobile technology. Powered by the Snapdragon 8 Gen 3 processor, it delivers groundbreaking AI performance for on-device processing, real-time translation, advanced photo editing, and intelligent productivity tools that learn and adapt to your workflow.</p>
<p>The integrated S Pen makes the S24 Ultra truly one-of-a-kind among premium smartphones. Stored seamlessly inside the device, the S Pen enables precision writing, detailed sketching, and effortless note-taking directly on the stunning 6.8-inch Dynamic AMOLED 2X display. The display itself delivers an adaptive 120Hz refresh rate, 2600 nits of peak brightness for exceptional outdoor visibility, and rich, accurate colors that make every image come alive.</p>
<p>Photography on the S24 Ultra is in a class of its own. The 200MP main camera captures extraordinary detail, while the innovative Quad Tele system provides optical zoom at 3x, 5x, and 10x focal lengths — all without any quality compromise. The 12MP Ultra Wide camera ensures you never miss a dramatic landscape or group shot, and advanced AI Scene Optimizer automatically enhances every photo.</p>
<p>Galaxy AI transforms the S24 Ultra into an intelligent assistant. Circle to Search lets you identify anything on screen instantly, Live Translate breaks language barriers in real-time calls, and Transcript Assist turns spoken meetings into organized text summaries. These AI features work seamlessly on-device, ensuring your private data stays private.</p>
<p>The 5000mAh battery with 45W wired and 15W wireless charging keeps you powered throughout even the busiest days. Titanium frame construction provides durability without excess weight, while the Corning Gorilla Armor coating protects the display from scratches and reduces reflections for clearer outdoor viewing.</p>',
'short_description' => '<p>The Samsung Galaxy S24 Ultra is the ultimate Android flagship, combining Snapdragon 8 Gen 3 performance with an integrated S Pen and a 200MP quad-camera system featuring 10x optical zoom. The 6.8-inch Dynamic AMOLED 2X display with 2600 nits brightness and Galaxy AI features including Circle to Search and Live Translate make it the smartest smartphone available. A titanium frame, 5000mAh battery with 45W fast charging, and IP68 water resistance complete this powerhouse package.</p>',
],

'oneplus-nord-ce-4' => [
'content' => '<p>The OnePlus Nord CE 4 delivers a remarkable combination of premium features and outstanding value, making flagship-level performance accessible to a wider audience. Built around the capable Snapdragon 7s Gen 2 processor, the Nord CE 4 handles everyday tasks, social media, gaming, and multitasking with smooth efficiency, while intelligent power management ensures your battery lasts throughout a full day of active use.</p>
<p>The centerpiece of the Nord CE 4 is its gorgeous 6.7-inch AMOLED display with a buttery-smooth 120Hz adaptive refresh rate. The screen produces vibrant colors, deep blacks, and excellent brightness levels that make streaming videos, browsing photos, and gaming genuinely enjoyable. Whether you are reading in bright sunlight or watching movies at night, the display adapts perfectly to deliver the best possible visual experience.</p>
<p>Camera performance punches well above the price point. The 50MP Sony IMX890 main camera captures detailed, color-accurate photos with impressive dynamic range. OIS ensures sharp handheld shots even in motion, while AI scene recognition optimizes settings automatically for every shooting scenario. The 8MP Ultra Wide camera adds versatility for landscapes and group photos, and a 16MP front camera delivers sharp, flattering selfies.</p>
<p>Where the Nord CE 4 truly shines is charging speed. The 100W SUPERVOOC flash charging system fills the 5500mAh battery from zero to 100 percent in approximately 28 minutes — meaning a brief 10-minute charge delivers several hours of additional usage. This eliminates battery anxiety entirely and makes overnight charging optional rather than necessary.</p>
<p>OxygenOS 14, based on Android 14, provides a clean, fast, and highly customizable software experience. The 256GB internal storage, 5G connectivity, and in-display fingerprint sensor round out a package that offers exceptional value. Available in Celadon Marble, Dark Chrome, and Jade Green color finishes.</p>',
'short_description' => '<p>The OnePlus Nord CE 4 is the ultimate budget flagship, pairing a Snapdragon 7s Gen 2 processor with a 120Hz AMOLED display and incredible 100W SUPERVOOC fast charging that fills the 5500mAh battery in under 30 minutes. The 50MP Sony IMX890 main camera with OIS delivers excellent photos across all conditions, while OxygenOS 14 provides a smooth and clean Android experience. 5G connectivity, 8GB RAM, and 256GB storage make this an exceptional value smartphone.</p>',
],

'macbook-pro-14-m3' => [
'content' => '<p>The MacBook Pro 14-inch with M3 chip represents the next leap forward in Apple silicon performance, delivering capabilities that were previously impossible in a laptop of this size. The M3 chip introduces hardware-accelerated ray tracing and mesh shading to the Mac for the first time, enabling stunning real-time graphics rendering for creative professionals and developers who need the best possible performance.</p>
<p>The Liquid Retina XDR display is breathtaking in every sense. With 1000 nits of sustained brightness for SDR content, 1600 nits peak brightness for HDR highlights, and support for the P3 wide color gamut, every image, video, and graphic appears with stunning accuracy and vibrancy. ProMotion technology adapts the refresh rate from 24Hz to 120Hz for incredibly smooth scrolling and video playback, while reducing power consumption when displaying static content.</p>
<p>Up to 22 hours of battery life means you can work through full days, long flights, and extended creative sessions without reaching for a charger. When you do need to recharge, MagSafe charging delivers safe, convenient magnetic connection with fast-charging capability. The comprehensive port selection includes three Thunderbolt 4 USB-C ports, HDMI 2.1, an SDXC card slot, and a headphone jack with high-impedance headphone support.</p>
<p>The M3 chip\'s unified memory architecture enables lightning-fast performance across CPU-intensive compilation tasks, GPU-demanding video rendering, and Neural Engine-accelerated machine learning workflows. With configurations starting at 8GB of unified memory and up to 24GB, the MacBook Pro 14 handles everything from coding to 8K video editing with remarkable efficiency.</p>
<p>The six-speaker sound system with Spatial Audio delivers concert-hall quality audio for music and immersive experiences. The 1080p FaceTime HD camera with Center Stage keeps you perfectly framed during video calls. macOS Sonoma adds powerful new productivity features including interactive widgets, improved game support, and enhanced video conferencing capabilities.</p>',
'short_description' => '<p>The MacBook Pro 14-inch with M3 chip delivers groundbreaking performance in a compact form factor, with hardware-accelerated ray tracing, a stunning Liquid Retina XDR ProMotion display, and up to 22 hours of battery life. Three Thunderbolt 4 ports, HDMI 2.1, and an SDXC slot provide comprehensive connectivity, while the six-speaker Spatial Audio system and 1080p camera ensure excellent media and communication experiences. Available in Space Black and Silver finishes with up to 24GB unified memory.</p>',
],

'dell-xps-15-oled' => [
'content' => '<p>The Dell XPS 15 OLED is the definitive creative professional laptop, combining extraordinary display quality with powerful performance hardware in an elegant, precision-engineered chassis. The 15.6-inch OLED display is truly extraordinary — delivering infinite contrast ratios, perfect blacks, and over 100% of the DCI-P3 color gamut with VESA DisplayHDR 500 True Black certification. Whether you are editing photographs, color-grading video, or designing graphics, the display reproduces colors with stunning fidelity that IPS panels simply cannot match.</p>
<p>Performance is driven by the 13th Generation Intel Core i7-13700H processor, a hybrid architecture chip that intelligently distributes workloads across performance and efficiency cores. Paired with NVIDIA GeForce RTX 4060 discrete graphics and 16GB of DDR5 RAM, the XPS 15 accelerates GPU-intensive creative workflows including 3D rendering, video effects processing, and AI-enhanced photo editing through NVIDIA DLSS and CUDA technologies.</p>
<p>The CNC-machined aluminum chassis and carbon fiber palm rest create a laptop that feels as premium as it looks. The compact design maintains a remarkably thin profile despite accommodating a large battery and powerful components. The keyboard is a pleasure to type on for extended sessions, with comfortable key travel and responsive feedback.</p>
<p>Thermal management is handled by dual fans and dedicated heat pipes that maintain sustained performance even during demanding creative projects. The 86Wh battery provides several hours of real-world productivity use, and Rapid Charge technology restores 80% capacity in approximately one hour using the included 130W USB-C adapter.</p>
<p>Connectivity options include two Thunderbolt 4 ports, a USB-A 3.2 port, an SD card reader, and a headphone jack. Windows 11 comes pre-installed, and optional Dell Optimizer software uses AI to learn your usage patterns and optimize battery, performance, and audio settings automatically.</p>',
'short_description' => '<p>The Dell XPS 15 OLED combines a stunning 15.6-inch 3.5K OLED display with infinite contrast and perfect DCI-P3 color accuracy alongside Intel Core i7-13700H performance and NVIDIA RTX 4060 graphics. The CNC-machined aluminum chassis houses 16GB DDR5 RAM, 512GB SSD, and Thunderbolt 4 connectivity in a slim, elegant package. Ideal for photographers, video editors, and creative professionals who demand the best display quality available in a portable form factor.</p>',
],

'lenovo-ideapad-slim-5' => [
'content' => '<p>The Lenovo IdeaPad Slim 5 is the ideal everyday laptop for students, remote workers, and professionals who need reliable performance in a lightweight, portable package without breaking the bank. Built around the AMD Ryzen 5 7530U processor, the IdeaPad Slim 5 delivers smooth performance for office productivity, web browsing, video streaming, and light creative work, while AMD\'s efficient architecture ensures impressive battery life throughout your day.</p>
<p>The 15.6-inch Full HD IPS display offers accurate colors, wide viewing angles, and comfortable brightness levels for extended work sessions. With 300 nits of brightness and anti-glare treatment, the display remains readable in various lighting conditions, from indoor offices to outdoor patios. TUV Rheinland Eye Comfort certification means reduced blue light emission for more comfortable extended use.</p>
<p>Sixteen gigabytes of LPDDR4X RAM ensures smooth multitasking even with multiple browser tabs, office applications, and communication tools running simultaneously. The 512GB NVMe SSD provides fast boot times, quick application launches, and ample storage for documents, photos, and projects. An additional M.2 slot allows future storage expansion if your needs grow.</p>
<p>Weighing just 1.65kg with a slim 17.9mm profile, the IdeaPad Slim 5 slips easily into a backpack for campus, office, or cafe use. The long-lasting 57Wh battery delivers up to 12 hours of real-world use, and Rapid Charge technology restores 80% battery capacity in approximately one hour. A dedicated privacy shutter on the webcam protects your privacy when not in video calls.</p>
<p>The full-size keyboard with number pad provides a comfortable typing experience for productivity tasks. Connectivity includes USB-A 3.2, USB-C with Power Delivery, HDMI 2.0, and a 4-in-1 card reader. Dolby Audio-enhanced speakers deliver clear, balanced sound for calls and media consumption. Available in Abyss Blue and Cloud Grey color options.</p>',
'short_description' => '<p>The Lenovo IdeaPad Slim 5 is an excellent everyday laptop offering AMD Ryzen 5 7530U performance, 16GB RAM, and a 512GB SSD in a slim 1.65kg chassis. The 15.6-inch Full HD IPS display with TUV Eye Comfort certification and up to 12 hours of battery life make it ideal for students and remote workers. Full-size keyboard, USB-C charging, HDMI output, and a privacy webcam shutter complete this well-rounded, budget-friendly package.</p>',
],

'asus-rog-strix-g16' => [
'content' => '<p>The ASUS ROG Strix G16 is a purpose-built gaming powerhouse engineered to deliver maximum performance for competitive and enthusiast gamers who refuse to compromise. At its heart lies the Intel Core i9-13980HX processor — the fastest mobile processor available — featuring 24 cores that handle gaming, streaming, recording, and creative tasks simultaneously without any performance bottleneck.</p>
<p>The NVIDIA GeForce RTX 4070 GPU with 8GB GDDR6 VRAM drives the stunning 16-inch QHD display at up to 240Hz refresh rate for buttery-smooth, tear-free gameplay. NVIDIA DLSS 3 Frame Generation technology boosts frame rates dramatically in supported titles, while ray tracing capabilities add realistic lighting, reflections, and shadows to compatible games. The MUX Switch bypasses the integrated graphics entirely, delivering up to 30% additional performance over standard configurations.</p>
<p>ROG\'s Intelligent Cooling system combines liquid metal thermal compound on the CPU, dual fans with self-cleaning technology, and five heat pipes to maintain peak performance during extended gaming marathons. Tri-fan technology keeps temperatures low even during the most demanding sessions, while multiple thermal modes let you balance performance against noise levels based on your current activity.</p>
<p>The per-key RGB backlit keyboard with Aura Sync allows complete lighting customization across 16.8 million colors and numerous animated effects. Anti-ghosting technology and 0.2ms response time ensure every keypress registers accurately in fast-paced competitive games. The large touchpad and optional gaming mouse ensure precision control for all game types.</p>
<p>Connectivity is exceptional with Wi-Fi 6E, Bluetooth 5.3, Thunderbolt 4, HDMI 2.1 for 4K120Hz external display output, and multiple USB-A ports for peripherals. The 90Wh battery provides portable gaming between sessions, and the 240W power adapter ensures full performance when plugged in.</p>',
'short_description' => '<p>The ASUS ROG Strix G16 is an elite gaming laptop powered by Intel Core i9-13980HX and NVIDIA RTX 4070, driving a 16-inch QHD 240Hz display for supremely smooth competitive gameplay. ROG Intelligent Cooling with liquid metal thermal compound maintains peak performance during extended sessions, while per-key RGB Aura Sync lighting and MUX Switch maximize both aesthetics and GPU performance. Wi-Fi 6E, Thunderbolt 4, HDMI 2.1, and a 90Wh battery complete this uncompromising gaming machine.</p>',
],

'sony-wh-1000xm5' => [
'content' => '<p>The Sony WH-1000XM5 wireless headphones define the gold standard for active noise cancellation, delivering an immersive listening experience that effectively silences the outside world whether you are commuting, working in a busy office, or traveling internationally. Eight microphones combined with two dedicated processors — the HD Noise Cancelling Processor QN1 and the Integrated Processor V1 — create Sony\'s most sophisticated noise cancellation system ever developed, automatically adapting to your environment in real time.</p>
<p>Sound quality is extraordinary. The 30mm drivers are custom-engineered specifically for the WH-1000XM5, delivering a wide frequency response with rich, detailed bass, smooth midrange, and crisp, clear highs. LDAC codec support enables wireless audio at up to 990kbps — three times more data than standard Bluetooth audio — preserving the nuance and detail of high-resolution music files without compromise.</p>
<p>Speak-to-Chat technology automatically detects your voice and pauses music instantly when you start speaking, resuming playback when your conversation ends. Quick Attention mode lets you cup your hand over the right earcup to temporarily pass through environmental audio for brief conversations without removing the headphones. Multipoint connection allows simultaneous pairing with two devices, switching seamlessly between your phone and laptop.</p>
<p>Call quality is exceptional thanks to four beamforming microphones and precise voice pickup technology that isolates your voice from background noise for crystal-clear calls and video conferencing. The 30-hour battery life with ANC enabled means you can listen for days between charges, and a quick 3-minute charge provides 3 hours of playback when you are running low.</p>
<p>The redesigned lightweight construction with soft earpads ensures extended wearing comfort during long listening sessions. Touch controls on the right earcup allow intuitive volume, playback, and call management. The Sony Headphones Connect app provides deep customization of EQ settings, noise cancellation levels, and personalized sound profiles based on your hearing profile.</p>',
'short_description' => '<p>The Sony WH-1000XM5 delivers industry-leading active noise cancellation through eight microphones and dual processors, combined with exceptional Hi-Res Audio via LDAC codec. Thirty hours of battery life, Speak-to-Chat automatic pause, multipoint dual-device connection, and crystal-clear call quality make these the complete wireless headphone package. Lightweight construction with premium soft earpads ensures all-day comfort, while the Sony Headphones Connect app enables deep personalization of sound and ANC settings.</p>',
],

'apple-airpods-pro-gen-3' => [
'content' => '<p>The Apple AirPods Pro 3rd Generation represent the most sophisticated audio product Apple has ever created for the ears, delivering a transformative listening experience through advanced hardware and intelligent software working in perfect harmony. The H2 chip enables next-generation Active Noise Cancellation that is twice as effective as the previous generation, creating a quiet personal space even in the most noisy and chaotic environments including airplanes, busy streets, and crowded offices.</p>
<p>Adaptive Audio is an entirely new listening mode that dynamically blends Active Noise Cancellation and Transparency mode based on your surroundings. When you walk through a quiet space, Adaptive Audio lets more environmental sound through for situational awareness. When noise increases, it smoothly increases cancellation to keep you focused. Conversation Awareness automatically reduces volume and enhances voices when you begin speaking, making natural conversations effortless.</p>
<p>Sound quality has been substantially improved with a new custom driver and amplifier. The low-distortion audio at all frequencies means music sounds more natural and detailed, with precise spatial imaging through Personalized Spatial Audio with dynamic head tracking. The system uses your iPhone\'s TrueDepth camera to create a personal acoustic profile that maps audio precisely to your unique ear shape.</p>
<p>The MagSafe charging case provides full protection and delivers up to 30 hours of total listening time including six hours in the earbuds themselves. The case charges wirelessly via MagSafe, Qi, and Apple Watch chargers, and includes a Lightning connector for wired charging. Precision Finding uses Ultra Wideband technology to locate the case\'s exact position when misplaced.</p>
<p>The customizable touch controls on the stem allow intuitive management of playback, calls, and ANC modes. IP54 water and dust resistance protects both the earbuds and case from sweat and splashes during workouts. Instant pairing and automatic device switching across all your Apple devices make the AirPods Pro 3rd Gen the seamless choice for the Apple ecosystem.</p>',
'short_description' => '<p>AirPods Pro 3rd Generation features the H2 chip delivering Active Noise Cancellation twice as powerful as before, alongside the new Adaptive Audio mode that intelligently blends ANC and Transparency based on your environment. Conversation Awareness, Personalized Spatial Audio with head tracking, and 30 hours total battery life with the MagSafe charging case make these the ultimate earbuds for Apple users. IP54 resistance, Precision Finding, and seamless ecosystem switching complete the package.</p>',
],

'anker-7-in-1-usb-c-hub' => [
'content' => '<p>The Anker 7-in-1 USB-C Hub is an essential productivity tool for anyone working with a modern laptop, instantly transforming a single USB-C port into a complete workstation connectivity hub. Designed with both power users and everyday professionals in mind, this compact hub delivers reliable, high-speed connectivity without the bulk or complexity of larger docking stations, fitting easily into a pocket or laptop bag for use anywhere.</p>
<p>The 4K HDMI port supports video output at 4K resolution and 30Hz refresh rate, enabling crisp external monitor connections for presentations, extended desktop setups, or mirroring your display in meeting rooms and conference spaces. For content creators and photographers, the SD and TF card reader slots provide fast simultaneous access to camera memory cards, eliminating the need to carry separate card readers.</p>
<p>Three USB-A 3.0 ports deliver 5Gbps data transfer speeds for fast file transfers from external drives, connection of USB peripherals including keyboards, mice, and external storage devices, and charging of smartphones and tablets. The pass-through USB-C Power Delivery port supports up to 100W charging, ensuring your laptop charges at full speed through the hub without requiring a separate power adapter.</p>
<p>Anker\'s advanced temperature management system prevents overheating during extended use, while built-in surge protection safeguards your connected devices from power fluctuations. The plug-and-play design requires no drivers or software installation — simply connect the hub to your laptop\'s USB-C port and all seven ports become immediately available.</p>
<p>Bus-powered operation means no external power supply is needed, keeping your workspace clean and clutter-free. The compact aluminum housing measures just 11cm in length and weighs 66 grams, making it genuinely portable. Compatible with MacBook Pro, MacBook Air, iPad Pro, Dell XPS, Surface Pro, and any USB-C Windows laptop. An 18-month warranty and Anker\'s renowned customer support provide peace of mind.</p>',
'short_description' => '<p>The Anker 7-in-1 USB-C Hub instantly expands a single USB-C port into seven essential connections: 4K HDMI output, three USB-A 3.0 ports for 5Gbps transfers, SD and TF card reader slots, and a 100W USB-C Power Delivery pass-through port. Bus-powered and driver-free, this compact 66g aluminum hub works with any USB-C laptop including MacBook, iPad Pro, Dell XPS, and Surface. Built-in surge protection and Anker\'s 18-month warranty ensure reliable, safe connectivity anywhere.</p>',
],

];

foreach ($products as $slug => $data) {
    $post = Post::where('slug', $slug)->where('type', 'product')->first();
    if (!$post) { echo "Not found: $slug\n"; continue; }

    $post->update(['content' => $data['content']]);

    $pd = ProductData::where('post_id', $post->id)->first();
    if ($pd) {
        $pd->update(['short_description' => $data['short_description']]);
    }

    echo "Updated: {$post->title}\n";
}

echo "\nAll descriptions updated!\n";
